### ISSUE TITLE
提些小建议吧

### ISSUE THREAD

**Issue by lizyn** [gudzpoz/17GRE#1]
1. 每天List数为1的时候，生成计划是L1～1，原版exam.us只显示L1，更简洁
2. 中国人的习惯应该还是把周一作为每周第一天吧，如果能改下也许更好
3. （小声）我觉得用非衬线字体会好看些

夸赞的话就不说了hhh，URL参数的设计非常实用，还有自定义计划功能，赞

**Comment by gudzpoz** [comment]
谢谢反馈！但是我现在暂时没有太多时间改代码……之后有时间的时候我应该会用新版本的框架（Vue 3）重写一遍代码，那时候会尽量实现这些功能。（所以我先鸽一会儿 :P ）

**Comment by gudzpoz** [comment]
拖到现在终于改好了！现在单个 list 显示成了 `L 43` 以及 `L* 43`。
每周第一天以及字体方面其实我个人没有什么偏好，所以还是直接做成了选项：用户可以选择从周一或者周日开始一星期，也可以自定义字体。字体默认还是让用户自己的浏览器设定决定。
